### PR TITLE
Delete LICENSE

### PR DESCRIPTION
**Pull request by jadenquinn**

### CODE REVIEW

**Comment by jadenquinn** [comment]
Now by Jaden (Red)!    

-jaden-

**Comment by jadenquinn** [comment]
Oops! Just getting into Github, trying to create a build operation on my side! How, may I ask, would I do that?

Thanks!


-jaden-

**Comment by jadenquinn** [comment]
Shadow, any chance you have a discord server or account I can add you/join into/on?

-jaden-

**Comment by shadowfacts** [comment]
Are you trying to build the project? You just run `gradlew build` in the project directory.

**Pull request closed without merging**
