### PR TITLE
Add automatic version replacement in Forgelin.kt

### LINKED ISSUE #19: Forgelin.kt version
https://github.com/shadowfacts/Forgelin/blob/master/src/main/kotlin/net/shadowfacts/forgelin/Forgelin.kt#L13

the version inside that class file does not match the jar name. which is causing mods that require forgelin 1.5.0 to think its not found.

I think you can use gradle or even forge gradle to replace that version for you.

Edit. Looks like ForgeGradle can't replace easily when its a build.gradle.

### PR DESCRIPTION
**Pull request by marvin-roesch**
This enables source replacements in Kotlin files, which in turns allows for automatically expanding `@VERSION@` in `Forgelin.kt`. Fixes #19. In the future, mismatches between file names and in-JAR versions will never happen again!

### CODE REVIEW

**Comment by shadowfacts** [comment]
Awesome, thanks! I’ll release a new build tomorrow. 

In the future would it be possible to have this fixed directly in ForgeGradle? It’d be nice to have replacements in Kotlin files without needing a whole bunch of extra code in the build.gradle.

**Comment by shadowfacts** [comment]
Forgelin 1.5.1 has been released.

**Comment by marvin-roesch** [comment]
Great to hear that :D
I'll see if I can work this into FG proper, but since it's written in Java, calling the Kotlin-related methods requires some different approach. It can do it for Scala because the Gradle API includes a way to get the Scala sources, it didn't have this for Kotlin last time I checked, though.

**Comment by shadowfacts** [comment]
Oh well, that's too bad. This is certainly better than updating the version manually, though.

**Comment by marvin-roesch** [comment]
Great news, I was actually able to get this into ForgeGradle. See MinecraftForge/ForgeGradle#437. I'll PR the required changes again when it gets merged, if you want me to.

**Comment by shadowfacts** [comment]
That would be awesome, thanks!

**Pull request merged**
